### ISSUE TITLE
Error in command "roslynator analyze"

### ISSUE THREAD

**Issue by ghost** [dotnet/roslynator#1073]
**Product and Version Used**: 
roslynator.dotnet.cli   "version": "0.5.0

**Steps to Reproduce**:
roslynator analyze

**Actual Behavior**:
```csharp
```

One or more errors occurred. (Unknown value 'Default'. (Parameter 'reportDiagnostic'))
  Inner exception: Unknown value 'Default'. (Parameter 'reportDiagnostic')

**Expected Behavior**:
```csharp
```

**Comment by jsliwinski** [comment]
The issue can be reproduced when you control the severity of analysis in csproj file. 
Here is an example to reproduce the issue: https://gist.github.com/jsliwinski/b9edaf77d2ccfad9dc1130bee4cf0a16

Here is a proposed quick fix for that situation:
https://github.com/dotnet/roslynator/pull/1411
