### ISSUE TITLE
Serialization attributes with StreamingContext cause RCS1163 messages

### ISSUE THREAD

**Issue by murrty** [dotnet/roslynator#1199]
**Product and Version Used**: 
Roslynator 4.5.0, Visual Studio 17.7.3, tested on NET 7 and Framework 4.7.2

**Steps to Reproduce**:
Create a method with any of the `OnSerialized`/`OnDeserialized`/`OnSeriailizing`/`OnDeserializing` attributes that require `StreamingContext` as a parameter.

**Actual Behavior**:
Gives the unused parameter message.

**Expected Behavior**:
Should not give the unused parameter message because the parameter is required.

This seems to have occurred before (#276, #281) but they seem to be just slightly different.

**Comment by josefpihrt** [comment]
https://learn.microsoft.com/en-us/dotnet/api/system.runtime.serialization.onserializedattribute?view=net-8.0
