### ISSUE TITLE
Suggest using "await using" rather than "using"

### ISSUE THREAD

**Issue by molinch** [dotnet/roslynator#1267]
**Product and Version Used**: 
Roslynator 4.6.2

**Steps to Reproduce**:
Have a type that implements both IDisposable and IAsyncDisposable.
Leverage C# using keyword rather than await using.

**Actual Behavior**:
Example with EF.Core IDbContextTransaction interface, which implements both IDisposable and IAsyncDisposable.
```csharp
using var transaction = await context.Database.BeginTransactionAsync(System.Data.IsolationLevel.ReadCommitted, cancellationToken);
```

**Expected Behavior**:
If there could be an analyzer that suggests going to the async version then we would have optimal code.
```csharp
await using var transaction = await context.Database.BeginTransactionAsync(System.Data.IsolationLevel.ReadCommitted, cancellationToken);
```

Please note that there is a similar Roslyn Analyzer issue opened since long: https://github.com/dotnet/roslyn-analyzers/issues/4891

**Comment by josefpihrt** [comment]
Hi,

The question is how to handle non-async method because it would mean to change method's return type which would  break other code. So I would probably leave it to methods that are already async.

before:
```cs
public void Foo()
{
    using var d = new Disposable();
}
```

after:
```cs
public async Task Foo()
{
    await using var d = new Disposable();
}
```

**Comment by molinch** [comment]
@josefpihrt that makes a lot of sense. Would you base it on the fact that the method is already having keyword async, or woul you base it on return type of the method? (if it's awaitable)

**Comment by josefpihrt** [comment]
At first I would check if it has `async` keyword. If not, I would check if the return type is awaitable.
