### ISSUE TITLE
roslynator analyze throws after update.

### ISSUE THREAD

**Issue by Pentadome** [dotnet/roslynator#1329]
**Product and Version Used**: 
```
"roslynator.dotnet.cli": {
      "version": "0.8.1",
      "commands": [
        "roslynator"
      ]
    },
    <GlobalPackageReference Include="Roslynator.Analyzers" PrivateAssets="all" Version="4.7.0" />
```

```
One or more errors occurred. (Method not found: 'System.Collections.Generic.IEnumerator`1<Microsoft.CodeAnalysis.NodeStateEntry`1<System.ValueTuple`2<System.__Canon,System.__Canon>>> Microsoft.CodeAnalysis.NodeStateTable`1.GetEnumerator()'.)
  Inner exception: Method not found: 'System.Collections.Generic.IEnumerator`1<Microsoft.CodeAnalysis.NodeStateEntry`1<System.ValueTuple`2<System.__Canon,System.__Canon>>> Microsoft.CodeAnalysis.NodeStateTable`1.GetEnumerator()'.

```

**Comment by andrewlangemann** [comment]
I am also getting this error with version 0.8.1 - see attached for the output with `-v diag` as requested:
[roslynator-output.txt](https://github.com/dotnet/roslynator/files/13706114/roslynator-output.txt)

**Comment by josefpihrt** [comment]
@andrewlangemann Thanks for the log.

Do you think you could create a small project that would reproduce the error and upload the project here? I would like to test it on my local machine. Thanks.

**Comment by Pentadome** [comment]
I fixed the error by installing .net 8. I thought the machine had .net 8 installed

**Comment by josefpihrt** [comment]
Great!

Closing as resolved.

**Comment by andrewlangemann** [comment]
How is this closed? Does Roslynator no longer support .NET 7?

**Comment by josefpihrt** [comment]
> Does Roslynator no longer support .NET 7?

Do you mean Roslynator CLI? It does:

https://github.com/dotnet/roslynator/blob/2354f1feb0d84e5c7565b24c1af0221ca9a9f4f1/src/CommandLine/CommandLine.csproj#L7-L9
