### ISSUE TITLE
Is this compatible with C# Dev Kit VSCode extension?

### ISSUE THREAD

**Issue by smashedtoatoms** [dotnet/roslynator#1338]
**Product and Version Used**: Visual Studio Code 1.85.0 with C# Dev Kit Extension 1.1.16 on Windows 10

**Steps to Reproduce**: Install Roslynator VSCode plugin, Install C# Dev Kit Extension, configure config file

**Actual Behavior**:
no Roslynator warnings or suggestions appear

**Expected Behavior**:
file should get lit up with warnings and suggestions

The reason I phrased the question the way I did is because I can't tell if it should work or not.  If I disable C# Dev Kit, and enable the `Use Omnisharp` config value, then it works fine.  The problem is that I rely on other functionality from C# Dev Kit (primarily the test runner), so having to disable it is not great.  If this is a product of MS not playing nicely with open source, I totally get it.  It would be nice if it mentioned that in the docs somewhere.  If it's already in the docs or being discussed somewhere, my apologies for not finding it.  If you could point me towards it, I would appreciate it.  Thanks so much.

**Comment by josefpihrt** [comment]
Hi,

Roslyn code analysis should work with C# Dev Kit (see https://github.com/microsoft/vscode-dotnettools/issues/61)

I tested it locally and I can see diagnostics as well as code fixes in the VS Code. I have following configuration:

- VS Code 1.85.0
- Roslynator 4.7.0
- C# 2.13.10
- C# Dev Kit 1.2.2

![image](https://github.com/dotnet/roslynator/assets/11931318/b74dd5b2-eb0c-4191-aa98-958f13d6cd7a)

**Comment by smashedtoatoms** [comment]
OH!  Ok, so I didn't have C# Dev Kit in Preview mode.  I flipped that on and now everything works!  Thanks so much!

**Comment by josefpihrt** [comment]
Great! 👍
