### ISSUE TITLE
Fixing RCS1251 produces RCS0023 in csproj

### ISSUE THREAD

**Issue by daze99** [dotnet/roslynator#1348]
**Product and Version Used**: 
Roslynator 4.8.0

**Steps to Reproduce**:
When applying the fix to
```csharp
namespace Test;

public static class Test
{
}
```
it produces the result
```csharp
namespace Test;

public static class Test;
```
This results then in a RCS0023 on the csproj file.

**Comment by josefpihrt** [comment]
duplicate of #920
