### ISSUE TITLE
consistent exceptions about 'IfStatementCodeFixProvider' encountered an error and has been disabled.

### ISSUE THREAD

**Issue by mikeblas** [dotnet/roslynator#1363]
**Product and Version Used**: 

I'm using `roslynator.analyzers` 4.9.0 on a project that uses .Net 8.0.100

**Steps to Reproduce**:

When I edit my code in Visual Studio 2022 (Version 17.8.3) I'll soon see a message bar at the top of the IDE that says

 > 'IfStatementCodeFixProvider' encountered an error and has been disabled.

The call stack given is here:

     System.MissingMethodException : Method not found: 'Roslynator.CSharp.Analysis.If.IfAnalysisOptions Roslynator.CSharp.Analysis.IfStatementAnalyzer.get_AnalysisOptions()'.
        at async Roslynator.CSharp.CodeFixes.IfStatementCodeFixProvider.RegisterCodeFixesAsync(<Unknown Parameters>)
        at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
        at Roslynator.CSharp.CodeFixes.IfStatementCodeFixProvider.RegisterCodeFixesAsync(CodeFixContext context)
        at async Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetCodeFixesAsync(<Unknown Parameters>)
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)

**Comment by josefpihrt** [comment]
Hmm, I tried to reproduce the problem locally but I was not successful. Do you think you could create a small project that contains minimum code but where the problem still happens, and upload the project here? Thanks.

**Comment by mikeblas** [comment]
The problem occurs when I'm working on my [JankSQL project](https://github.com/mikeblas/JankSQL). While I certainly understand that a minimal repro case would be helpful, I have no idea how to eliminate what code in my solution would or wouldn't be involved in causing the failure.

I think the project is pretty bland; maybe one unique feature is that there's a lot of code generated by [Antlr](https://www.antlr.org/) for the SQL grammar I'm parsing. There are also NUnit tests, but everyone uses those.

**Comment by josefpihrt** [comment]
I cloned your repo and then tried to cause the problem by pasting a code sample that can be fixed by `IfStatementCodeFixProvider`. Unfortunately, there was no error during the fix.

Do you think you could make a clean clone of your repo on your machine and then see if the error still occurs?

**Comment by mikeblas** [comment]
Thanks for having a look!

I was getting this exception every day for about a week, so I opened this issue. Since then (over the last three or four days) I haven't hit the exception again. I'm not sure what has changed, but if it starts happening again I'll re-open the issue.
