### ISSUE TITLE
About new packages

### ISSUE THREAD

**Issue by bdovaz** [dotnet/roslynator#1382]
@josefpihrt the new packages are useful in Unity? Unity has its own .NET compiler, you don't compile the code from the VS IDE, the IDE "only" serves to code and attach to Unity processes.

Because I understand that from what you put the use cases are these? Or am I misunderstanding?

Thank you.

**Comment by josefpihrt** [comment]
Just to be sure, are you talking about these packages?

https://www.nuget.org/packages/Roslynator.Refactorings
https://www.nuget.org/packages/Roslynator.CodeFixes

**Comment by bdovaz** [comment]
Yes, that's right.

**Comment by josefpihrt** [comment]
I don't know how development in Unity works. Do you use VS, VS Code or does it have its own IDE?

Anyway, the purpose of these packages is to have access to refactorings and code fixes for compiler diagnostic in an environment where you cannot use Roslynator IDE extension (VS or VS Code). For example the development with C# Dev Kit in VS Code. C# Dev Kit does not support loading of Roslyn features from the extension so only way is to use nuget packages.

**Comment by bdovaz** [comment]
Ok, thank you!
