### ISSUE TITLE
Simplify numeric comparison

### ISSUE THREAD

**Issue by josefpihrt** [dotnet/roslynator#1394]
`(a - b) == 0` => `a == b`
`(a - b) > 0` => `a > b`
`(a - b) >= 0` => `a >= b`
`(a - b) < 0` => `a < b`
`(a - b) <= 0` => `a <= b`

```

**Comment by josefpihrt** [comment]
Maybe add to `RCS1195`

**Comment by jakubreznak** [comment]
Hello, I'm interested in resolving this issue and would appreciate it if you could assign it to me.

**Comment by josefpihrt** [comment]
Great!

I just thinking about whether to create new analyzer or whether to add this functionality to some existing analyzer. I think that it could be added to https://josefpihrt.github.io/docs/roslynator/analyzers/RCS1195. And the analyzer would be renamed to "Simplify binary expression".

**Comment by jakubreznak** [comment]
I would create a new analyzer and then add it to BinaryExpressionCodeFixProvider.
Is it ok?

**Comment by josefpihrt** [comment]
And what would be a name of the analyzer?

**Comment by jakubreznak** [comment]
I would name it the SimplifyNumericComparisonAnalyzer.

**Comment by josefpihrt** [comment]
Agreed.
