### ISSUE TITLE
CS8032: An instance of analyzer Roslynator.CSharp.Analysis.UnnecessaryRawStringLiteralAnalyzer cannot be created

### ISSUE THREAD

**Issue by khellang** [dotnet/roslynator#1406]
**Product and Version Used**:

- Roslynator.Analyzers 4.10.0
- Visual Studio 2022 17.8.7

**Steps to Reproduce**:

We have a sln with two .NET 8, three .NET Standard 2.0 projects and a single non-SDK-based csproj, targeting .NET Framework 4.8. When updating `Roslynator.Analyzers` to version `4.10.0` in our `Directory.Build.props` file across the entire solution, we're now getting this build error for the .NET Framework project.

**Actual Behavior**:

Getting a build error:

```
CS8032: An instance of analyzer Roslynator.CSharp.Analysis.UnnecessaryRawStringLiteralAnalyzer cannot be created from E:\PackageCache\NuGet\roslynator.analyzers\4.10.0\analyzers\dotnet\roslyn4.7\cs\Roslynator.CSharp.Analyzers.dll : Could not load type 'Roslynator.CSharp.Analysis.UnnecessaryRawStringLiteralAnalyzer' from assembly 'Roslynator.CSharp.Analyzers, Version=4.10.0.0, Culture=neutral, PublicKeyToken=926ea54d246a765e'..
```

**Expected Behavior**:

No build error?

**Comment by josefpihrt** [comment]
@khellang Could you use nugets from [PR](https://github.com/dotnet/roslynator/actions/runs/7957770103?pr=1407) and load it from local nuget to see if it helps?

**Comment by khellang** [comment]
I can confirm that does indeed fix the error we're seeing, @josefpihrt. Thank you 🙏
