### ISSUE TITLE
RCS1169 not being diffused by roslynator_unity_code_analysis.enabled = true

### ISSUE THREAD

**Issue by somedeveloper00** [dotnet/roslynator#1418]
**Product and Version Used**: 
vscode with C# dev kit | Unity project | roslynator as nuget package (latest to date)
**Steps to Reproduce**: 
add the following to `.editorconfig` 
```editorconfig
[*.cs]
roslynator_unity_code_analysis.enabled = true
```
then write a script that a field with `[SerializeField]` attribute, like 
```csharp
using UnityEngine;

namespace Namespace
{
    public class Test : MonoBehaviour
    {
        [SerializeField] private float speed;

        private void Update()
        {
            transform.position += speed * Time.deltaTime * Vector3.forward;
        }
    }
}
```
**Actual Behavior**:
```csharp
using UnityEngine;

namespace Namespace
{
    public class Test : MonoBehaviour
    {
        [SerializeField] private readonly float speed;

        private void Update()
        {
            transform.position += speed * Time.deltaTime * Vector3.forward;
        }
    }
}
```
(note that `Update` did not get removed, showing that `[RCS1213](https://josefpihrt.github.io/docs/roslynator/analyzers/RCS1213)` is being diffused)
**Expected Behavior**:
```csharp
using UnityEngine;

namespace Namespace
{
    public class Test : MonoBehaviour
    {
        [SerializeField] private float speed;

        private void Update()
        {
            transform.position += speed * Time.deltaTime * Vector3.forward;
        }
    }
}
```

**Comment by somedeveloper00** [comment]
I think it has something to do with Unity not using `Attribute` with the `SerializeField` class name. I looked at the source codes for roslynator and saw that at https://github.com/dotnet/roslynator/blob/c2b0479bbadecf1725e9b4f541741e7c7242ef90/src/Analyzers/CSharp/Analysis/MakeMemberReadOnly/MakeMemberReadOnlyAnalyzer.cs#L21 its searching for `UnityEngine.SerializeFieldAttribute`, but in Unity, it's declared as `UnityEngine.SerializeField`

**Comment by josefpihrt** [comment]
> I think it has something to do with Unity not using Attribute with the SerializeField class name.

Yes, that's the problem.

Do you have any idea why suffix `Attribute` is omitted in the name of this attribute?

**Comment by somedeveloper00** [comment]
> Do you have any idea why suffix `Attribute` is omitted in the name of this attribute?
I have no idea. Might be an old thing that remained in the engine for compatibility purpures, but then they change a lot of APIs in each major version, so I don't know why don't they change this as well. But yeah, there's not official reason publicly available anywhere

**Comment by somedeveloper00** [comment]
I checked and asked around, the attribute has always been just `SerializeField`. So it's safe to change the analyzer code to look only for `UnityEngine.SerializeField`
