### ISSUE TITLE
Project contains numerous invalid exports of ILanguageService

### ISSUE THREAD

**Issue by sharwell** [dotnet/roslynator#1437]
`ILanguageService` needs to be exported using `ExportLanguageServiceAttribute`.

Here is one example:

https://github.com/dotnet/roslynator/blob/7505ae82a935905c8e4733f3c4bf719f6b5fb446/src/CSharp.Workspaces/CSharp/CodeMetrics/CSharpCodeMetricsService.cs#L12

These exports are breaking Visual Studio in 17.10 Preview 3 and newer, where additional validation is applied to `ILanguageService` and `ILanguageServiceFactory` exports.

**Comment by IeuanWalker** [comment]
Breaks the latest VS preview - https://developercommunity.visualstudio.com/t/Projects-loading-failing-after-update--/10636927?q=Projects+loading+failing+after+update&sort=newest&ref=native&refTime=1712845785529&refUserId=41977fbd-5ec3-6a58-abad-5a72a9276adf&viewtype=solutions

**Comment by sharwell** [comment]
@josefpihrt The `ExportMetadata` lines can be removed. You just need this:

```
[ExportLanguageService(typeof(ICodeMetricsService), LanguageNames.CSharp)]
```

**Comment by josefpihrt** [comment]
@sharwell Thanks!

**Comment by gpuchtel** [comment]
Nobody asked, but I just want to say (unsolicited) that this is the 2nd time the roslynator has 'hosed' Visual Studio after an update. Worse the 'roll-back' of Visual Studio failed to restore my extensions, or preferences.! When I mentioned this to the VS team, they blamed the 'roslynator' of not implementing some APIs correctly. Doesn't anybody test this stuff!? I'm uninstalling this thing.

**Comment by josefpihrt** [comment]
Fix has been released.
