### ISSUE TITLE
RCS1246 suggestion for Last() is not usable in .NET Framework 4.8

### ISSUE THREAD

**Issue by KavenBreton-eaton** [dotnet/roslynator#1450]
**Product and Version Used**:  Roslynator 4.12.1 and .NET Framework 4.8

**Steps to Reproduce**:
Use the Last() method of a List object for instance.

**Actual Behavior**:
Suggestion is to use [^1] but this is not usable in .NET Framework 4.8. We did not want to suppress the issue since other suggestions are of use for us.

**Expected Behavior**:
Having either a suggestion for .NET Framework 4.8 or don't raise it for this version.

**Comment by josefpihrt** [comment]
Possible solution is to check if `System.Index` exists.

**Comment by KavenBreton-eaton** [comment]
It seems like this exact same issue is back even though we are using the latest version (4.12.4). Should I create a new issue?
