### ISSUE TITLE
CLI Exlude, Include paramteters are not working

### ISSUE THREAD

**Issue by dimOk00** [dotnet/roslynator#1457]
**Product and Version Used**:  Roslynator Command Line Tool version 0.8.7.0 (Roslyn version 4.9.0.0), Widnows 11

**Steps to Reproduce**:
I want to analyze a specific file in my solution, I am using CLI for it.
I use next command `roslynator analyze --exclude "**\*" --include "**\UserStatuses.cs" `

**Actual Behavior**: It analyzes a whole solution

**Expected Behavior**: It analyzes only one file

Could you tell please, what is wrong with this command and how can I run analyze for multiple files?

**Comment by josefpihrt** [comment]
Even with the bug fixed, the command won't work. Correct command is `roslynator analyze --include "**\UserStatuses.cs"`.
