### ISSUE TITLE
RCS1077 for OrderBy(x => x)

### ISSUE THREAD

**Issue by bricelam** [dotnet/roslynator#1492]
RCS1077 should recommend replacing `.OrderBy(x => x)` with `.Order()`.

**Comment by josefpihrt** [comment]
@BenjaminBrienen You are more than welcome to do so!

Please see this file where you can a reference to the analyzer and cod fix provider:

https://github.com/dotnet/roslynator/blob/6a0519c09bc59186e3e3ee912caa099dffdf043e/src/Tests/Analyzers.Tests/RCS1077OptimizeLinqMethodCallTests.cs#L11

Also, following file can be useful even though you are not adding new analyzer:

https://josefpihrt.github.io/docs/roslynator/how-to-add-new-analyzer

**Comment by BenjaminBrienen** [comment]
![image](https://github.com/user-attachments/assets/9b78da78-570e-4e3f-921a-d88b1e3a2212)
I love it when I can just `git clone` a repository and all the tests pass! (except the test I just added)

**Comment by BenjaminBrienen** [comment]
Analysis is working, working on code fix

**Comment by BenjaminBrienen** [comment]
Apparently Order() only exists new newer versions of .NET. The code fix works though!

**Comment by BenjaminBrienen** [comment]
I found something that I could use
https://github.com/dotnet/roslynator/pull/1157#discussion_r1295714425
