### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by marcospgp** [dotnet/roslynator#1506]
https://josefpihrt.github.io/docs/roslynator/analyzers/RCS1237/

> This analyzer is obsolete. Use [RCS1254](https://josefpihrt.github.io/docs/roslynator/analyzers/RCS1237/RCS1254) instead.

The link is broken, should be https://josefpihrt.github.io/docs/roslynator/analyzers/RCS1254

**Comment by josefpihrt** [comment]
Fixed with #1508
