### ISSUE TITLE
RCS1077 - FirstOrDefault() is faster than Find() with .NET 9

### ISSUE THREAD

**Issue by symbiogenesis** [dotnet/roslynator#1531]
With .NET 8 and below, the recommendation to use Find() is correct.

But with .NET 9 or later, LINQ is actually faster.

https://www.youtube.com/watch?v=UfjRoshu23w&t=575s

**Comment by josefpihrt** [comment]
Interesting. Maybe it makes sense to remove this suggestion.

**Comment by symbiogenesis** [comment]
Would it make sense to actively suggest the reverse on .NET9 and above?

**Comment by josefpihrt** [comment]
@symbiogenesis Please create a new issue.
