### ISSUE TITLE
 Enable all analyzers by default when using Nuget packages

### ISSUE THREAD

**Issue by daze99** [dotnet/roslynator#1539]
**Product and Version Used**: 4.12.6

I just switched from the VS extension to the Nuget packages. Before there was a possibility to enable all analyzers with setting `roslynator_analyzers.enabled_by_default = true` in .roslynatorconfig.

How do I do this when using the Nuget packages as they do not support using a Roslynator config file?

**Comment by josefpihrt** [comment]
Recommended approach is to copy list of "default configuration" from this page: https://josefpihrt.github.io/docs/roslynator/configuration (section "full list of options"). Here, all analyzers have their default severity you can replace it with desired severity.

**Comment by daze99** [comment]
Ok, thanks
