### ISSUE TITLE
RCS1043 should also remove calls to partial methods

### ISSUE THREAD

**Issue by nvmkpk** [dotnet/roslynator#791]
**Product and Version Used**: 
Visual Studio Extension 3.1.0

**Steps to Reproduce**:
Consider the class below:
```csharp
public partial class Foo
{
    public Foo()
    {
        this.Initialize();
    }

    partial void Initialize();
}
```

**Actual Behavior**:
When there is no other partial class is defined for Foo in the project, this analyzer provides an option to remove the partial keyword. When it is selected, it removed the keyword as well as the partial method. But does not remove call to it resulting into a compiler error.
```csharp
public class Foo
{
    public Foo()
    {
        this.Initialize();
    }
}
```

**Expected Behavior**:
The code fix should also remove calls to the partial method.
```csharp
public class Foo
{
    public Foo()
    {
    }
}
```

**Comment by ryanbuening** [comment]
I came across RCS1043 in a Blazor app with a [partial class](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/?view=aspnetcore-5.0#partial-class-support). Roslynator gives me the option to remove the `partial` modifier, but it is needed for code-behind Blazor class.

![image](https://user-images.githubusercontent.com/812974/119837964-066a3c80-bed1-11eb-8e12-14043eb96df9.png)

**Comment by JosefPihrt** [comment]
@ryanbuening I think it would be possible to suppress the diagnostic if a class is derived from `ComponentBase`. Can you please create a new issue for it?

**Comment by ryanbuening** [comment]
Created #807

**Comment by nvmkpk** [comment]
> @ryanbuening I think it would be possible to suppress the diagnostic if a class is derived from `ComponentBase`. Can you please create a new issue for it?

What about when we don't have a razor file and are defining the component entirely in c#?

**Comment by JosefPihrt** [comment]
> What about when we don't have a razor file and are defining the component entirely in c#?

In that case you have to suppress diagnostic  or disable the analyzer.
