### ISSUE TITLE
(vscode) Not respecting .roslynatorconfig file

### ISSUE THREAD

**Issue by somedeveloper00** [dotnet/roslynator#944]
**Product and Version Used**: latest to this day (4.1.1). vscode extention

**Steps to Reproduce**: open vscode. install omnisharp. install roslynator. change some configs in the roslynator config file, then check if it's applied after a vscode restart. the usual process really

**Actual Behavior**: does not respect the .roslynatorconfig file rulesets
```csharp
```

**Expected Behavior**: respecting the .roslynatorconfig file rulesets
```csharp
```

here are screenshots:
![image](https://user-images.githubusercontent.com/79690923/185096901-6ad25765-28e8-4621-8feb-d97eeaf43368.png)
![image](https://user-images.githubusercontent.com/79690923/185096909-d6632516-e46a-4ad1-a4ed-df053b6e8c14.png)

**Comment by somedeveloper00** [comment]
I can also record my process and gif it out for further proof/info

**Comment by JosefPihrt** [comment]
Hi,

It seems to me that the reported diagnostic is actually IDE0044 which is not Roslynator diagnostic.

**Comment by somedeveloper00** [comment]
> Hi,
> 
> It seems to me that the reported diagnostic is actually IDE0044 which is not Roslynator diagnostic.

oh, right. didn't know until now that omnisharp itself has some pre-defined diagnostics too... can you be so kind to give me a link/explanation to search for, to disable a specific IDEXXXX diagnostic? thanks
